In [137]:
import math  
import numpy as np

data = np.array([[170,165,174,169,155,172,166,168],
                [60,55,75,67,49,63,58,61],
                [4.1,3.0,2.8,2.9,3.1,3.6,3.7,4.0]
                ])

def Average(lst): 
    return sum(lst) / len(lst)

def std(lst, avg):
    result = 0
    for i in range(0, len(lst)):
        result = result + math.pow((lst[i]-avg), 2)
    result = result / (len(lst)-1)
    result = math.sqrt(result)
    return result

In [138]:
n = len(data)
avg = np.arange(n, dtype=np.float32)

for i in range(0, n):  
    avg[i] = Average(data[i])
    i+=1
    
print('Height mean : ' + str(avg[0]))
print('Weight mean : ' + str(avg[1]))
print('Grade mean : ' + str(avg[2]))

Height mean : 167.375
Weight mean : 61.0
Grade mean : 3.4


In [139]:
m = len(data[0])

cov = (np.dot((data.transpose() - avg).transpose(), (data.transpose() - avg))) * (1/(m-1)) 

print('\033[1m' + 'Covariance Matrix : ')
print('\033[0m')
print(cov)

Covariance Matrix : 

[[33.69642857 39.42857143  0.37142857]
 [39.42857143 60.85714286 -0.94285714]
 [ 0.37142857 -0.94285714  0.26285714]]


In [140]:
stdev = np.arange(n, dtype=np.float32)

for i in range(0, n):  
    stdev[i] = std(data[i], avg[i])
    i+=1

print('Height std : ' + str(stdev[0]))
print('Weight std : ' + str(stdev[1]))
print('Grade std : ' + str(stdev[2]))

Height std : 5.8048625
Weight std : 7.801099
Grade std : 0.51269597


In [141]:
cov_len = len(cov)

corr = np.zeros(shape=(cov_len,cov_len))

for i_m in range(0, cov_len):
    for i_n in range(0, cov_len):
        corr[i_m][i_n] = cov[i_m][i_n] / (stdev[i_m] * stdev[i_n])
        
print('\033[1m' + 'Correlation Matrix : ')
print('\033[0m')
print(corr)

Correlation Matrix : 

[[ 0.99999995  0.87068955  0.12480256]
 [ 0.87068955  0.99999999 -0.23573834]
 [ 0.12480256 -0.23573834  0.9999999 ]]
